import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

import { ThemeProvider } from '@/components/providers'
import { cn } from '@/lib/utils'
import { NavigationMenuContextProvider } from '@/contexts/navigation-menu-context'
import { Header } from '@/components/site-header'

const neueMachina = localFont({
  src: [
    {
      path: '../public/neue-machina/PPNeueMachina-PlainRegular.otf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../public/neue-machina/PPNeueMachina-PlainUltrabold.otf',
      // weight: '700',
      style: 'normal'
    },
  ],
  variable: '--font-neue-machina'
})

const neueMontreal = localFont({
  src: [
    {
      path: '../public/neue-montreal/PPNeueMontreal-Bold.otf',
      weight: '700',
      style: 'normal'
    }
  ],
  variable: '--font-neue-montreal'
})

const charter = localFont({
  src: [
    {
      path: '../public/charter_regular.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../public/charter_bold.woff2',
      weight: '700',
      style: 'normal'
    },
  ],
  variable: '--font-charter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased flex flex-col items-start justify-start",
        charter.variable,
        neueMachina.variable,
        neueMontreal.variable
      )}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <NavigationMenuContextProvider>
            <Header />
            {children}
          </NavigationMenuContextProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
